version: "3.9"

services:
  engine:
    build: .
    container_name: melody_engine
    ports:
      - "8000:8000"

  server:
    build: .
    container_name: melody_server
    ports:
      - "3000:3000"
    environment:
      - PYTHON_ENGINE_URL=http://engine:8000
    depends_on:
      - engine
